### ISSUE TITLE
Grammar cleanup

### ISSUE THREAD

**Issue by waldemarhorwat** [tc39/proposal-discard-binding#4]
A stylistic nit:

Is there a reason the *BindingPattern* has the extra parameter *void*? The cleaner and simpler approach would seem to be to leave *BindingPattern* as is and introduce a new *BindingPatternOrVoid* production which expands to either *BindingPattern* or void, but I'm not sure if there is some future planned consideration that I'm overlooking. I originally created the notion of parameters on grammar productions to avoid duplicating a deep tree of productions, which doesn't apply here.

Also, where can I find the base grammar that this one is a difference of?

**Comment by rbuckton** [comment]
I believe this was addressed by #9 as well.
